sudo: required
services:
    - docker

language: generic

before_install:
    - docker build -t kevinzhang99/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true kevinzhang99/react-test npm test
    
after_success:
    - docker build -t kevinzhang99/multi-client ./client
    - docker build -t kevinzhang99/multi-nginx ./nginx
    - docker build -t kevinzhang99/multi-server ./server
    - docker build -t kevinzhang99/multi-worker ./worker
    # Log in the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take the image and push them to docker hub .
    - docker push kevinzhang99/multi-client
    - docker push kevinzhang99/multi-nginx
    - docker push kevinzhang99/multi-server
    - docker push kevinzhang99/multi-worker

