sudo: required
services:
    - docker

before_install:
    - docker build -t kevinzhang99/react-test -f ./client/Dockerfile.dev ./
    
script:
    - docker run -e CI=true kevinzhang99/react-test npm test
    
after_success:
    - docker build -t kevinzhang99/multi-client ./client
    - docker build -t kevinzhang99/multi-nginx ./nginx
    - docker build -t kevinzhang99/multi-server ./server
    - docker build -t kevinzhang99/multi-worker ./worker
    # Log in the docker CLI
    
    # Take the image and push them to docker hub
